export const currentPhotoResponse = {
  id: "Y2vplq0SAm0",
  slug: "waterfalls-on-forest-Y2vplq0SAm0",
  alternative_slugs: {
    en: "waterfalls-on-forest-Y2vplq0SAm0",
    es: "cascadas-en-el-bosque-Y2vplq0SAm0",
    ja: "森の滝-Y2vplq0SAm0",
    fr: "chutes-deau-sur-la-foret-Y2vplq0SAm0",
    it: "cascate-sulla-foresta-Y2vplq0SAm0",
    ko: "숲-위의-폭포-Y2vplq0SAm0",
    de: "wasserfalle-im-wald-Y2vplq0SAm0",
    pt: "cachoeiras-na-floresta-Y2vplq0SAm0",
  },
  created_at: "2019-05-26T20:36:08Z",
  updated_at: "2024-03-26T07:55:57Z",
  promoted_at: null,
  width: 5184,
  height: 3456,
  color: "#407326",
  blur_hash: "LHENF8%M4Tt6x~oy-rt7XKM|agad",
  description: null,
  alt_description: "waterfalls on forest",
  breadcrumbs: [],
  urls: {
    raw: "https://images.unsplash.com/photo-1558902944-405b1261c58a?ixid=M3w1ODQwODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTE1NDU5Nzd8&ixlib=rb-4.0.3",
    full: "https://images.unsplash.com/photo-1558902944-405b1261c58a?crop=entropy&cs=srgb&fm=jpg&ixid=M3w1ODQwODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTE1NDU5Nzd8&ixlib=rb-4.0.3&q=85",
    regular:
      "https://images.unsplash.com/photo-1558902944-405b1261c58a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1ODQwODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTE1NDU5Nzd8&ixlib=rb-4.0.3&q=80&w=1080",
    small:
      "https://images.unsplash.com/photo-1558902944-405b1261c58a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1ODQwODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTE1NDU5Nzd8&ixlib=rb-4.0.3&q=80&w=400",
    thumb:
      "https://images.unsplash.com/photo-1558902944-405b1261c58a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1ODQwODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTE1NDU5Nzd8&ixlib=rb-4.0.3&q=80&w=200",
    small_s3:
      "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1558902944-405b1261c58a",
  },
  links: {
    self: "https://api.unsplash.com/photos/waterfalls-on-forest-Y2vplq0SAm0",
    html: "https://unsplash.com/photos/waterfalls-on-forest-Y2vplq0SAm0",
    download:
      "https://unsplash.com/photos/Y2vplq0SAm0/download?ixid=M3w1ODQwODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTE1NDU5Nzd8",
    download_location:
      "https://api.unsplash.com/photos/Y2vplq0SAm0/download?ixid=M3w1ODQwODV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTE1NDU5Nzd8",
  },
  likes: 5,
  liked_by_user: false,
  current_user_collections: [],
  sponsorship: null,
  topic_submissions: {},
  asset_type: "photo",
  user: {
    id: "0aaqM7sduI0",
    updated_at: "2024-03-27T01:17:55Z",
    username: "pskpartha",
    name: "Partha Sarathi Kar",
    first_name: "Partha Sarathi",
    last_name: "Kar",
    twitter_username: null,
    portfolio_url: null,
    bio: null,
    location: "Tallinn, Estonia",
    links: {
      self: "https://api.unsplash.com/users/pskpartha",
      html: "https://unsplash.com/@pskpartha",
      photos: "https://api.unsplash.com/users/pskpartha/photos",
      likes: "https://api.unsplash.com/users/pskpartha/likes",
      portfolio: "https://api.unsplash.com/users/pskpartha/portfolio",
      following: "https://api.unsplash.com/users/pskpartha/following",
      followers: "https://api.unsplash.com/users/pskpartha/followers",
    },
    profile_image: {
      small:
        "https://images.unsplash.com/profile-1553710926655-3138eedd104a?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
      medium:
        "https://images.unsplash.com/profile-1553710926655-3138eedd104a?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
      large:
        "https://images.unsplash.com/profile-1553710926655-3138eedd104a?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
    },
    instagram_username: "parthaskar",
    total_collections: 0,
    total_likes: 8,
    total_photos: 41,
    total_promoted_photos: 0,
    accepted_tos: true,
    for_hire: false,
    social: {
      instagram_username: "parthaskar",
      portfolio_url: null,
      twitter_username: null,
      paypal_email: null,
    },
  },
  exif: {
    make: "Canon",
    model: "Canon EOS 600D",
    name: "Canon, EOS 600D",
    exposure_time: "1/125",
    aperture: "5.0",
    focal_length: "55.0",
    iso: 100,
  },
  location: {
    name: "Keila Waterfall, Tallinn, Estonia",
    city: "Tallinn",
    country: "Estonia",
    position: { latitude: null, longitude: null },
  },
  meta: { index: true },
  public_domain: false,
  tags: [
    { type: "search", title: "estonia" },
    { type: "search", title: "tallinn" },
    { type: "search", title: "keila waterfall" },
    { type: "landing_page", title: "nature", source: [Object] },
    { type: "landing_page", title: "waterfall", source: [Object] },
    { type: "landing_page", title: "water", source: [Object] },
    { type: "search", title: "river" },
    { type: "search", title: "outdoors" },
    { type: "search", title: "stream" },
    { type: "landing_page", title: "tree", source: [Object] },
    { type: "search", title: "plant" },
    { type: "search", title: "creek" },
    { type: "search", title: "land" },
  ],
  tags_preview: [
    { type: "search", title: "estonia" },
    { type: "search", title: "tallinn" },
    { type: "search", title: "keila waterfall" },
  ],
  views: 67352,
  downloads: 744,
  topics: [],
};
